export const tractorMakes = [
  { id: 1, label: "John Deere", slug: "john-deere" },
  { id: 2, label: "Massey Ferguson", slug: "massey-ferguson" },
  { id: 3, label: "New Holland", slug: "new-holland" },
  { id: 4, label: "Kubota", slug: "kubota" },
  { id: 5, label: "Case IH", slug: "case-ih" },
  { id: 6, label: "Claas", slug: "claas" },
  { id: 7, label: "Fendt", slug: "fendt" },
  { id: 8, label: "Mahindra", slug: "mahindra" },
  { id: 9, label: "Deutz-Fahr", slug: "deutz-fahr" },
  { id: 10, label: "Challenger (AGCO)", slug: "challenger-agco" },
  { id: 11, label: "Landini", slug: "landini" },
  { id: 12, label: "Valtra", slug: "valtra" },
  { id: 13, label: "McCormick", slug: "mccormick" },
  { id: 14, label: "Same", slug: "same" },
  { id: 15, label: "Zetor", slug: "zetor" },
  { id: 16, label: "Lamborghini Tractors", slug: "lamborghini-tractors" },
  { id: 17, label: "Armatrac", slug: "armatrac" },
  {
    id: 18,
    label: "Sonalika (International Tractors Ltd.)",
    slug: "sonalika-international-tractors-ltd",
  },
  {
    id: 19,
    label: "Escorts (Farmtrac, Powertrac)",
    slug: "escorts-farmtrac-powertrac",
  },
  { id: 20, label: "Ursus", slug: "ursus" },
  { id: 21, label: "Belarus (MTZ)", slug: "belarus-mtz" },
  { id: 22, label: "Yanmar", slug: "yanmar" },
  { id: 23, label: "TYM Tractors", slug: "tym-tractors" },
  { id: 24, label: "Kioti (Daedong)", slug: "kioti-daedong" },
  { id: 25, label: "Branson Tractors", slug: "branson-tractors" },
];
